export const INIT_FLIGHTS = 'INIT_FLIGHTS';

export const SORT_BY_ASCENDING_PRICE = 'SORT_BY_ASCENDING_PRICE';
export const SORT_BY_DESCENT_PRICE = 'SORT_BY_DESCENT_PRICE';
export const SORT_BY_DURATION_TIME = 'SORT_BY_DURATION_TIME';

export const FILTER_WHITH_TRANSFER = 'FILTER_WHITH_TRANSFER ';

export const FILTER_BY_MIN_PRICE = 'FILTER_BY_MIN_PRICE';
export const FILTER_BY_MAX_PRICE = 'FILTER_BY_MAX_PRICE';

export const FILTER_BY_AIRLINE = 'FILTER_BY_AIRLINE';
